server:
  port: 9101
spring:
  application:
    name: microservice-user
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.1.114:3306/test?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql

eureka:
  client:
    register-with-eureka: true #作为客户端需要注册到eureka
    fetch-registry: true #作为客户端需要从eureka获取注册信息
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka
    registry-fetch-interval-seconds: 5 # 修改获取注册信息的间隔时间
  instance:
    prefer-ip-address: true #优先使用该服务的IP地址注册到eureka
    lease-renewal-interval-in-seconds: 5 #服务续约时间，默认为30秒
    lease-expiration-duration-in-seconds: 10 #服务失效时间，默认90秒